feat: add support for images on events (RFC7986)
spatie/icalendar-generator pull request #71
Opened 2021-11-23 11:24 UTC by davwheat

RFC7986 adds the ability to attach Images to various iCal components, including Events.

This PR implements _partial_ support for this, via URI-based images rather than embedded binary/base64 images.

2021-11-23 19:14 UTC, freekmurze commented
Looks good to me, what do you think @rubenvanassche ?

2021-11-25 14:36 UTC, rubenvanassche requested changes
Looking great! two small remarks and then this one can be merged!

2021-11-25 14:36 UTC, rubenvanassche commented on src/Components/Event.php
> +     */
Could you remove this docblock and add a small section to the Readme.md page on how to use this?

2021-11-25 14:36 UTC, rubenvanassche commented on src/Components/Event.php
> +    public function image(string $url, ?string $mediaType = null, ?Display $display = null): Event
Could you rename `mediaType` to `mime`? Since that covers exactly what is required.

2021-11-25 15:22 UTC, davwheat commented
Should be sorted now :)

2021-11-25 15:24 UTC, rubenvanassche commented
Thanks!

2021-11-25 15:24 UTC, merged